<?php
// $Id$

/**
 * @file
 * Defines a field type for displaying markup on the node/edit form.
 */

/**
 * Implementation of hook_field_info().
 */
function markup_field_info() {
  return array(
    'markup' => array('label' => 'Markup'),
  );
}

/**
 * Implementation of hook_field_settings().
 */
function markup_field_settings($op, $field) {
  switch ($op) {
    case 'form':
      $form = array();
      $form['instructions'] = array(
        '#type' => 'markup',
        '#value' => t('This is a special field. It will output the markup below, unfiltered by the system, on the node/edit form for this content type.'),
        '#weight' => -1,
      );
      $form['markup'] = array(
        '#type' => 'textarea',
        '#title' => t('Markup'),
        '#default_value' => isset($field['markup']) ? $field['markup'] : '',
        '#required' => TRUE,
        '#rows' => 15,
        '#description' => t('The markup to be displayed. Any HTML is legal here, so be careful not to break your page layout.'),
      );
      $form['allow_php_code'] = array(
        '#type' => 'checkbox',
        '#title' => t('Allow PHP Code?'),
        '#default_value' => isset($field['allow_php_code']) ? $field['allow_php_code'] : '',
        '#description' => t('Advanced usage only: Allow PHP code in the markup field above. Should include &lt;?php ?&gt; delimiters. You can access the current node object using $node.'),
      );
      return $form;

    case 'validate':
      break;

    case 'save':
      return array('markup', 'allow_php_code');
    case 'database columns':
      return array();
  }
}

/**
 * Implementation of hook_widget_info().
 */
function markup_widget_info() {
  return array(
    'markup' => array(
      'label' => 'Markup',
      'field types' => array('markup'),
      'multiple values' => CONTENT_HANDLE_MODULE,
    ),
  );
}

/**
 * Implementation of hook_widget_settings().
 */
function markup_widget_settings($op, $widget) {
  switch ($op) {
    case 'form':
      $form = array();

      $form['display_style'] = array(
        '#type' => 'radios',
        '#title' => t('Display Style'),
        '#default_value' => !empty($widget['display_style']) ? $widget['display_style'] : '',
        '#options' => array(
          'none' => t('Hide Field Wrapper & Label'),
          'wrapper' => t('Display Field Wrapper & Hide Label'),
          'all' => t('Display Field Wrapper & Label'),
        ),
        '#required' => TRUE,
        '#description' => 
          t('Choose how the markup field should be displayed on the node form.') .
          '<br />' .
          htmlentities(t('A field wrapper consists of a <div class="form-item"></div> wrapper around the markup to follow form standards.')),
      );

      return $form;

    case 'save':
      return array('display_style');
  }
}

/**
 * Implementation of FAPI hook_elements().
 *
 * Any FAPI callbacks needed for individual widgets can be declared here,
 * and the element will be passed to those callbacks for processing.
 *
 * Drupal will automatically theme the element using a theme with
 * the same name as the hook_elements key.
 */
function markup_elements() {
  return array(
    'markup_widget' => array(
      '#input' => TRUE,
      '#process' => array('markup_widget_process'),
    ),
    'markup_element' => array(
       '#input' => TRUE,
       '#process' => array('markup_element_process'),
    ),
  );
}

/**
 * Implementation of hook_theme().
 */
function markup_theme() {
  return array(
    'markup_widget' => array(
      'arguments' => array('element' => NULL),
    ),
    'markup_element' => array(
      'arguments' => array('element' => NULL),
    ),
  );
}

/**
 * Implementation of hook_content_multigroup_allowed_widgets().
 */
function markup_content_multigroup_allowed_widgets() {
  return array('markup');
}

/**
 * Implementation of hook_content_multigroup_no_remove_widgets().
 */
function markup_content_multigroup_no_remove_widgets() {
  return array('markup');
}

/**
 * Implementation of hook_widget().
 */
function markup_widget(&$form, &$form_state, $field, $items, $delta = 0) {
  $element = array(
    '#type' => 'markup_widget',
    '#markup' => $field['markup'],
  );
  
  return $element;
}

/**
 * Process the markup_widget element.
 *
 * Build the form element. When creating a form using FAPI #process,
 * note that $element['#value'] is already set.
 *
 * The $fields array is in $form['#field_info'][$element['#field_name']].
 */
function markup_widget_process($element, $edit, $form_state, $form) {
  $field = $form['#field_info'][$element['#field_name']];

  // Find out which display_style we are using and whether we need to hide the
  // title and/or wrapper.
  $display_style = !empty($field['widget']['display_style']) ? $field['widget']['display_style'] : 'none';
  $hide_wrapper = 0;

  if ($display_style == 'wrapper') {
    unset ($element['#title']);
  }
  if ($display_style == 'none') {
    unset ($element['#title']);
    $hide_wrapper = 1;
  }

  $markup = $element['#markup'];

  if (!empty($markup)) {
    $element['markup'] = array(
      '#type' => 'markup_element',
      '#title' => $element['#title'],
      '#markup' => $markup,
      '#hide_wrapper' => $hide_wrapper,
      '#allow_php_code' => $field['allow_php_code'],
    );
    
    // Apply the output_callback attribute, if set, on to the child element.
    if (!empty($element['#output_callback'])) {
      $element['markup']['#output_callback'] = $element['#output_callback'];
    }
  }

  return $element;
}

/**
 * Process the markup_element element.
 *
 * Build the form element. When creating a form using FAPI #process,
 * note that $element['#value'] is already set.
 *
 * The $fields array is in $form['#field_info'][$element['#field_name']].
 */
function markup_element_process($element, $edit, $form_state, $form) {
  $output = '';
  $valid_callback = FALSE;

  if (!empty($element['#output_callback'])) {
    $callback = $element['#output_callback'];
    if (function_exists($callback)) {
      $valid_callback = TRUE;
      $output = $callback($element, $field, $form_state);
    }
  }

  if ($valid_callback) {
    return $output;
  }

  // Check to see if the markup is empty, if so return element.
  if (empty($element['#markup'])) {
    return $element;
  }

  // Check to see if there is a php value set, if so evaluate the code.
  if (!empty($element['#allow_php_code'])) {
    $node = array();
    // Check we are on a node edit form.
    if (isset($form_state['values']['nid']) || isset($form_state['values']['type'])) {
      // Build a node element from the $form_state
      include_once(drupal_get_path('module', 'node') .'/node.pages.inc');
      $node = node_form_submit_build_node($form, $form_state);
    }
    // Evaluate the php code, and pass in the $node object.
    $element['#value'] = markup_eval($element['#markup'], array('node' => $node));
  }
  else {
    $element['#value'] = $element['#markup'];
  }

  return $element;
}

/**
 * Prepare and evaluate of a string of PHP code.
 *
 * This method is mostly a copy of drupal_eval().
 *
 * @param string $code
 * @param array $arguments
 * @return string
 */
function markup_eval($code, $arguments = array()) {
  global $theme_path, $theme_info, $conf;

  // Extract the arguments and make available.
  extract($arguments);

  // Store current theme path.
  $old_theme_path = $theme_path;

  // Restore theme_path to the theme, as long as drupal_eval() executes,
  // so code evaluted will not see the caller module as the current theme.
  // If theme info is not initialized get the path from theme_default.
  if (!isset($theme_info)) {
    $theme_path = drupal_get_path('theme', $conf['theme_default']);
  }
  else {
    $theme_path = dirname($theme_info->filename);
  }

  // Evaluate the php code
  ob_start();
  print eval('?>'. $code);
  $output = ob_get_clean();

  // Recover original theme path.
  $theme_path = $old_theme_path;

  return $output;
}

/**
 * Implementation of hook_form_alter().
 */
function markup_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'content_field_edit_form' && $form['module']['#value'] == 'markup') {
    // Remove non-applicable fields on the widget settings form.
    unset($form['widget']['description']);
    unset($form['field']['required']);
    unset($form['field']['multiple']);
    unset($form['field']['#description']);
  }
}

/**
 * Implementation of cck hook_content_is_empty().
 */
function markup_content_is_empty($item, $field) {
  return TRUE;
}

/**
 * FAPI theme for an individual elements.
 *
 */

function theme_markup_widget($element) {
  return $element['#children'];
}

function theme_markup_element($element) {
  $value = (isset($element['#value']) ? $element['#value'] : '') . (isset($element['#children']) ? $element['#children'] : '');

  if ($element['#hide_wrapper']) {
    return $value;
  }
  else {
    return theme('form_element', $element,  $value);
  }
}